### ISSUE TITLE
Add CI test for some Windows versions

### ISSUE THREAD

**Issue by ms-ati** [enkessler/childprocess#111]
Looks like AppVeyor may be a popular service for this?

**Comment by enkessler** [comment]
AppVeyor looks like it will work. I just need to tweak a thing or two to get the build green before I merge the update.

**Comment by enkessler** [comment]
@ms-ati Done.

https://ci.appveyor.com/project/enkessler/childprocess/build/1.0.4

**Comment by ms-ati** [comment]
Awesome! What a wonderful world for multi platform CI we now live in ;)

**Comment by enkessler** [comment]
@ms-ati Yes it is. :)

Quick question for you: Because you brought up the lack of OSX testing and the OSX bug that slipped through due to that, I am guessing that you have an OSX machine? Would you be willing to write that test? 

I still only have Windows and Ubuntu and trying to develop and test something new in real time is still not something that I can do for OSX, even with the expanded CI.

**Comment by ms-ati** [comment]
Yes! Thanks for being responsive on this. I'll do my part
