### ISSUE TITLE
Misleading error message when executing script with broken shebang

### ISSUE THREAD

**Issue by igneus** [enkessler/childprocess#123]
I have a script. The script filename is `script` and it only contains a shebang, which is, unfortunately, broken - the referenced interpreter doesn't exist.

```bash
#!/bin/does_not_exist
```

I want to execute the script with childprocess.

```ruby
require 'childprocess'

process = ChildProcess.build("./script")
process.io.inherit!

process.start
process.wait
```

But I get this exception

```
/home/igneus/.rvm/gems/ruby-2.3.1/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:58:in `launch_process': No such file or directory - ./script (ChildProcess::LaunchError)
        from /home/igneus/.rvm/gems/ruby-2.3.1/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
        from test.rb:9:in `<main>'
```

The issue I would like to report is the exception's message. It says **No such file or directory - ./script**, which is wrong. The script perfectly exists and when I change it's shebang to something sane, e.g. `#!/bin/bash`, it executes without failure. In such cases the error message should report that the file cannot be executed, not that it doesn't exist.

Tested with childprocess 0.5.9, ruby 2.3.1, on Linux.

See also a related [aruba issue](https://github.com/cucumber/aruba/issues/501)

**Comment by enkessler** [comment]
Fun fact: I develop primarily on a Windows machine. This means that I get an entirely different error message for a missing file than you do, because that's how the operating system felt like communicating the error. And this is the crux of the issue because, like `aruba` before it, `childprocess` is simply handing over the error that it was told happened by whatever dependency it farmed out the functionality to. In this case, that dependency is whatever OS the program is running on.

Attempting to intelligently determine what went wrong based on the OS error message (which could change across OS versions or configurations) or based on what command the user was trying to execute (while having even less context of what was going on than the user), all so that `childprocess` could then provide an even better error message  would be...'non-trivial', to say the least. I would also say that it is outside the scope of this gem.

On the bright side, however, the fact that the message is the normal message for that OS for whatever problem it encountered means that you are pretty likely to find some kind of information after a quick internet search or, as a regular user of that operating system, be able to have a decent idea of what it meant yourself.

**Comment by igneus** [comment]
> ... you are pretty likely to find some kind of information after a quick internet search or, as a regular user of that operating system, be able to have a decent idea of what it meant yourself.

As I encountered this error , I was quite confused (although I consider myself an experienced Linux user) and "quick internet search" wasn't helpful, either.

Now I know that the encountered behaviour is known (section "Possible errors" in this [article on shebang](https://www.in-ulm.de/~mascheck/various/shebang/)). It looks like the error message in question is being emitted by the Linux core itself. When the shebang is handled by bash instead of the system, the message is more helpful:

```
$ ./script 
bash: ./script: /bin/does_not_exist: bad interpreter: No such file or directory
```

> I would also say that it is outside the scope of this gem.

I mostly agree. Hopefully at least this issue will be helpful for those searching the internet after encountering the same mysterious error message in the future.

**Comment by igneus** [comment]
I guess this issue can be closed now, as everything important has been said.
