### ISSUE TITLE
childprocess kills detached windows process on exit

### ISSUE THREAD

**Issue by soapy1** [enkessler/childprocess#166]
It seems like detaching a process on Windows is not working as expected. For example a process created will exit when the parent process exits even when running a process using `process.detach = true`. On other platforms such as MacOS, the process will continue when the parent process stops.

I have a sample project as follows:
```
require 'childprocess'

class ProcessTest
  def self.start
    # Build the command line for the new process
    process = ChildProcess.build("ruby", "-e", "sleep(10)")
    process.cwd = Dir.pwd
    # Make sure process gets a new group
    process.leader = true
    # Make sure the process keeps running
    process.detach = true
    # Start the process
    process.start
    # process.poll_for_exit(15) #<= for windows
  end

  if __FILE__ == $0
    puts 'Parent process started'
    ProcessTest.start
    puts 'Parent process finished'
  end
end
```

*expected*
running this on mac, I get the expected results:
```
-> % ruby test.rb          
Parent process started
Parent process finished
-> % ps aux | grep ruby
sophia           50469   0.0  0.0  4399356    800 s007  S+    5:53PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox ruby
sophia           50456   0.0  0.0  5147104  13260 s007  S     5:53PM   0:00.09 ruby -e sleep(10)
*wait 10 sec*
-> % ps aux | grep ruby
sophia           50482   0.0  0.0  4408572    812 s007  S+    5:54PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox ruby
```

*actual*
running this on windows, once the parent ruby process finishes, it kills the ruby process marked as detached. I would have expected to see the child ruby process running for some time after the parent process finished.
```
C:\test>ruby test.rb
Parent process started
Parent process finished
** note < 5 sec between commands
C:\test> tasklist /fi "IMAGENAME eq ruby.exe"
INFO: No tasks are running which match the specified criteria.
```

Using:
childprocess: 3.0.0
ruby: 2.6.x

ref: https://github.com/enkessler/childprocess/issues/99

**Comment by sds** [comment]
Thanks for opening an issue @soapy1!

Digging into this a little further, what I can see is that we [set the `DETACHED_PROCESS` flag](https://github.com/enkessler/childprocess/blob/8e809feba799fedb49ae4033f590c2706de8828e/lib/childprocess/windows/process_builder.rb#L104) passed to the [`CreateWindowsW` function call](https://github.com/enkessler/childprocess/blob/8e809feba799fedb49ae4033f590c2706de8828e/lib/childprocess/windows/lib.rb#L50).

The [Win32 API documentation for the DETACHED_PROCESS flag](https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags) suggests we are using it incorrectly. "Detach" in this context simply means the process isn't attached to the same console/terminal as the parent, whereas "detach" in the way ChildProcess uses it is more referring to the [`Process::detach`](https://ruby-doc.org/core-2.6.1/Process.html#method-c-detach) helper.

I unfortunately do not have easy access to a Windows machine at this time, but I wonder if simply calling `Process::detach` in ChildProcess::Windows::ProcessBuilder.start would do the trick. Since you are running this on Windows, would you be able to apply the following diff and running locally to see if it fixes your issue? It may not, as `Process::detach` may be specific to Unix systems. Would happily accept a pull request if it works, however!

See [lib/childprocess/windows/process_builder.rb](https://github.com/enkessler/childprocess/blob/8e809feba799fedb49ae4033f590c2706de8828e/lib/childprocess/windows/process_builder.rb#L26-L38)
```patch
        def start
          create_command_pointer
          create_environment_pointer
          create_cwd_pointer

          setup_flags
          setup_io

          pid = create_process
+         Process::detach(pid) if @detach
          close_handles

          pid
        end
```

Appreciate your help!

**Comment by soapy1** [comment]
Thanks for digging into this!
I applied the patch and it looks like it returns an error. 

```
C:\Users\vagrant\Desktop\test>ruby bug.rb
Parent process started
Traceback (most recent call last):
        5: from bug.rb:4:in `<main>'
        4: from bug.rb:20:in `<class:ProcessTest>'
        3: from bug.rb:14:in `start'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess/abstract_process.rb:81:in `start'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess/windows/process.rb:70:in `launch_process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess/windows/process_builder.rb:35:in `start': undefined method `detach' for ChildProcess::Windows::Process:Class (NoMethodError)
```

I made a slight modification to `::Process.detach(pid) if @detach`. This doesn't produce an error, however the problem persists.

**Comment by soapy1** [comment]
I dug into this a little more and I found that [JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE](https://github.com/enkessler/childprocess/blob/master/lib/childprocess/windows/process.rb#L104) is getting set. From the [windows docs on managing jobs](https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects#managing-job-objects) it looks like setting this flag will kill a child process when the parent terminates as part. Here is a little PR for not setting that flag if running in detached mode https://github.com/enkessler/childprocess/pull/167

**Comment by sds** [comment]
Thank you for digging into this and submitting a PR in #167. Closing as while we don't have any tests, I am assuming this solved the issue for you locally. Thanks again!
