### ISSUE TITLE
Handle filesystem full

### ISSUE THREAD

**Issue by dg-ratiodata** [enkessler/childprocess#90]
Hi,

given that script:

``` ruby
require 'childprocess'
require 'tempfile'

process = ChildProcess.build("echo", "World")

out      = Tempfile.new("blub.txt")
out.sync = true

process.io.stdout = process.io.stderr = out
process.start
process.poll_for_exit(1)

out.rewind
puts out.read #=> "hello world\n"
```

And a full filesystem at `/tmp`.

``` bash
dd if=/dev/zero of=/tmp/blub.dd
```

The command silently fails. Maybe it makes sense that  `ChildProcess` outputs a warning if it cannot write to a given IO.

**Comment by sds** [comment]
Following up on this issue many years later: while I completely understand the desire to provide better feedback in exceptional situations, implementing this doesn't make much sense since any error writing to the file would be detected by the spawned child process doing the writing (`echo World` in this case). The child process needs to handle the error, and the calling application can determine that the error occurred via some IPC mechanism (or simply inspecting the exit status of the child process).

One way you could have detection happen outside of the spawned child process is if you injected an intermediate process that polled and and forwarded any data it receives from the spawned process's STDOUT stream to the intended output file. If an error occurs, it can then report this error via some form of IPC back to the original process that spawned the child process.

Inserting an intermediate process this way is heavy-handed and would introduce an unnecessary performance penalty that most would not care to incur. It also adds complexity to anyone trying to understand the flow of data between your processes and files.

I'm going to close this ticket as "won't do." If you feel I've misunderstood the request, let us know!
